kind: pipeline
type: kubernetes
name: greeting

steps:
- name: en
  image: alpine
  commands:
  - echo hello world
  when:
      branch:
        - master
      event:
        - push
        - pull_request
        - tag

- name: fr
  image: alpine
  commands:
  - echo bonjour monde