# kind: pipeline
# type: docker
# name: greeting

# steps:
# - name: en
#   image: alpine
#   commands:
#   - echo hello world
#   when:
#       branch:
#         - master
#       event:
#         - push
#         - pull_request
#         - tag

# - name: fr
#   image: alpine
#   commands:
#   - echo bonjour monde

# kind: pipeline
# name: default
# steps:
#   - name: test
#     image: golang:1.10-alpine
#     commands:
#       - "go test"
#   - name: build
#     image: golang:1.10-alpine
#     commands:
#       - "go build -o ./myapp"
#   - name: publish
#     image: plugins/docker
#     settings:
#       repo: chukwurado/k8scicd
#       tags: [ "${DRONE_COMMIT_SHA:0:7}","latest" ]
#       username:
#         from_secret: docker_username
#       password:
#         from_secret: docker_password

#   - name: deliver
#     image: sinlead/drone-kubectl
#     settings:
#       kubernetes_server:
#         from_secret: k8s_server
#       kubernetes_cert:
#         from_secret: k8s_cert
#       kubernetes_token:
#         from_secret: k8s_token
#     commands:
#       - kubectl apply -f deployment.yml

kind: pipeline
type: kubernetes
name: default

steps:
  # - name: test
  #   image: node:12.18.1-buster
  #   commands:
  #     - cd client
  #     - npm install
  #     - npm run test

  - name: publish-client
    image: plugins/docker
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      dockerfile: ./client/Dockerfile
      context: ./client
      repo: chukwurado/multi-client
      tags:
        - "latest"
        - "${DRONE_COMMIT_SHA:0:7}"
  
  - name: publish-server
    image: plugins/docker
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      dockerfile: ./server/Dockerfile
      context: ./server
      repo: chukwurado/multi-server
      tags:
        - "latest"
        - "${DRONE_COMMIT_SHA:0:7}"
  
  - name: publish-worker
    image: plugins/docker
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      dockerfile: ./worker/Dockerfile
      context: ./worker
      repo: chukwurado/multi-worker
      tags:
        - "latest"
        - "${DRONE_COMMIT_SHA:0:7}"
      

  - name: deploy
    image: google/cloud-sdk:alpine
    environment:
      google_credentials:
        from_secret: google_credentials
    commands:
      - /bin/bash deploy.sh
      # - echo $google_credentials > /tmp/$CI_PIPELINE_ID.json
      # - gcloud auth activate-service-account --key-file /tmp/$CI_PIPELINE_ID.json
      # - gcloud config set project test-k8s-287319
      # - gcloud config set compute/zone us-central1-c
      # - gcloud components install kubectl
      # - gcloud container clusters get-credentials cluster-1
      # - kubectl apply -f k8s
      # - kubectl set image deployments/server-deployment server="chukwurado/multi-server:${DRONE_COMMIT_SHA:0:7}"
      # # - kubectl set image deployments/client-deployment client="chukwurado/multi-client:${DRONE_COMMIT_SHA:0:7}"
      # # - kubectl set image deployments/worker-deployment worker="chukwurado/multi-worker:${DRONE_COMMIT_SHA:0:7}"